const ar = {
    'skip':'تخطي',
    'phoneNumber': 'رقم الجوال',
    'password': 'كلمة المرور',
    'forgetPass': 'هل نسيت كلمة المرور ؟',
    'loginButton': 'دخول',
    'registerButton': 'تسجيل',
    'sendButton': 'ارسال',
    'verifyCode': 'كود التحقق',
    'newPass': 'كلمة المرور الجديدة',
    'verifyPass': 'تأكيد كلمة المرور',
    'verifyNewPass': 'تأكيد كلمة المرور الجديدة',
    'codeNotCorrect': 'كود التفعيل غير صحيح',
    'confirm': 'تأكيد',
    'username': 'اسم المستخدم',
    'email': 'البريد الالكتروني',
    'noNotifications': 'لا يوجد اشعارات',
    'language': 'لغة التطبيق',
    'stopNotification': 'غلق الاشعارات',
    'shareApp': 'مشاركة التطبيق',
    'home': 'الرئيسية',
    'aboutApp': 'عن التطبيق',
    'terms' : 'الشروط والأحكام',
    'contactUs' : 'اتصل بنا',
    'settings' : 'الاعدادات',
    'logout' : 'تسجيل الخروج',
    'notifications' : 'الاشعارات',
    'notificationDeleted' : 'تم حذف الاشعار',
    'search' : 'بحث',
    'country' : 'الدولة',
    'entityType': 'نوع الكيان',
    'rate': 'التقييم',
    'wallet': 'المحفظة',
    'profile': 'الملف الشخصي',
    'certify&exp': 'الشهادات والخبرات',
    'certifies': 'الشهادات',
    'expertise': 'الخبرات',
    'interests': 'الاهتمامات',
    'employerName': 'اسم جهة العمل',
    'jobTitle': 'المسمي الوظيفي',
    'messages': 'الرسائل',
    'writeMsg': 'اكتب رسالتك هنا',
    'addDet': 'تفاصيل الاعلان',
    'ChangePass': 'تغيير كلمة المرور',
    'socialAcc': 'حسابات التواصل الاجتماعي',
    'whatsApp': 'الواتساب',
    'facebook': 'فيس بوك',
    'twitter': 'تويتر',
    'instagram': 'انستغرام',
    'noAcc': 'لا تمتلك حساب ؟ تسجيل جديد',
    'add': 'اضافة',
    'addAd': 'اضافة اعلان',
    'jobName': 'اسم الوظيفة',
    'section': 'القسم',
    'workType': 'نوع العمل',
    'CompSug': 'الشكاوي والمقترحات',
    'address': 'العنوان',
    'subTitle': 'عنوان الموضوع',
    'subCont': 'محتوي الموضوع',
    'edit': 'تعديل',
    'delete': 'حذف',
    'cancel': 'الغاء',
    'yes': 'نعم',
    'no': 'لا',
    'date': 'التاريخ',
    'time': 'بداية العمل',
    'location': 'الموقع',
    'searchPlaceholder': 'اكتب ما تريد أن تبحث عنه',
    'activateAcc': 'تفعيل الحساب',
    'jobDet': 'تفاصيل الوظيفة',
    'perHour': 'بالساعة',
    'noHour': 'العمل بالطلب',
    'hoursNo': 'عدد الساعات',
    'pricePerHour': 'سعر الساعة',
    'finalFee': 'الأجر النهائي',
    'attachments': 'المرفقات',
    'noteThat': 'يرجي العـلم بأنه عند الضغط على اضافة الإعلان فهذا يعني قبولك بـه وسـيتم خصـم',
    'ofUrWallet': 'من رصيدك بالمحفظة',
    'adCongrats': 'تهانينا تم اضافة اعلانك بنجاح',
    'fare': 'الأجره',
    'ownerLocation': 'هذا الموقع تقريبي لموقع مالك الإعلان',
    'connectWithAd': 'تواصل مع المعلن',
    'deleteAd': 'هل انت متأكد من حذف الاعلان ؟',
    'interestName': 'اسم الاهتمام',
    'city': 'المدينة',
    'adNumber': 'رقم الإعلان',
    'activityName': 'اسم النشاط',
    'noteAdd': 'يرجي العـلم بأنه عند الضغط على الإعلان فهذا يعني قبولك بـه وسـيتم خصـم',
    'noCredit': 'عفواً لا يوجد رصيد كافي بالمحفظة ، يرجي إعادة شحن محفظتك لدينا',
    'recharge': 'اعادة شحن',
    'msgContent': 'محتوي الرسالة',
    'addCredit': 'تهانينا تم اضافة رصيدك بنجاح',
    'passRecovery': 'استرجاع كلمة المرور',
    'chooseLang': 'اختر اللغة',
    'login': 'تسجيل الدخول',
    'req&ann': 'طلباتي واعلاناتي',
    'req': 'طلباتي',
    'ann': 'اعلاناتي',
    'urRate': 'لا تنسي ان تضع تقييمك',
    'currentBalance': 'رصيدك الحالي',
    'DR': 'دولار',
    'reChargeWallet': 'إعادة شحن المحفظة',
    'bankInfo': 'يمكنك شحن رصيدك عن طريق تزويدنا بمعلومات حسابك البنكى',
    'transBank': 'اسم البنك المحول منه',
    'accUser': 'اسم صاحب الحساب',
    'accNum': 'رقم الحساب',
    'chargedCredit': 'المبلغ المطلوب شحنه',
    'transferReceipt': 'صورة إيصال التحويل',
    'newReg': 'تسجيل جديد',
    'agreement': 'بتسجيلك في التطبيق فـأنت موافق على',
    'attention': 'تنبيه',
	'passwordRequired': 'كلمة السر مطلوبه',
	'phoneRequired': 'رقم الهاتف مطلوب',
	'passwordLength': 'كلمة السر اقل من 6 احرف',
	'phoneValidation': 'رقم الهاتف غير صحيح',
	'searchResult': 'نتائج البحث',
	'categories': 'الاقسام',
	'countries': 'اختر الدولة',
	'activity': 'النشاط',
	'passwordNotMatch': 'كلمة مرور جديدة وتأكيد كلمة المرور غير متطابقة',
	'establishment': 'مؤسسه',
	'individual': 'فرد',
	'company': 'شركة',
	'distance': 'يبعد عنك',
	'km': 'كيلو',
	'gender': 'الجنس',
	'male': 'ذكر',
	'female': 'انثي',
	'both': 'كلاهما',
	'editAd': 'تعديل الاعلان',
	'noBalance': 'ليس لديك رصيد كافٍ لإضافة إعلان جديد',
	'jobNameValid': 'اسم الوظيفة يحتوي علي ارقام',
	'activityValid': 'النشاط يحتوي علي ارقام',

}

export default ar;