const en = {
    'skip':'Skip',
    'phoneNumber': 'Phone number',
    'password': 'Password',
    'forgetPass': 'Forget your password ?',
    'loginButton': 'Login',
    'registerButton': 'Register',
    'sendButton': 'Send',
    'username': 'Username',
    'email': 'Email',
    'confirm': 'Confirm',
    'language': 'App language',
    'stopNotification': 'Stop notification',
    'shareApp': 'Share app',
    'verifyCode': 'Verification code',
    'selectedKayanValidation': 'Type is required',
    'newPass': 'New password',
    'verifyNewPass': 'Confirm your new password',
    'verifyPass': 'Confirm your password',
    'noNotifications': 'No notifications',
    'home': 'Home',
    'aboutApp': 'About app',
    'terms' : 'Terms and conditions',
    'contactUs' : 'Contact us',
    'settings' : 'Settings',
    'logout' : 'Logout',
    'notifications' : 'Notifications',
    'notificationDeleted' : 'Notification deleted',
    'search' : 'Search',
    'country' : 'Country',
    'entityType' : 'Entity type',
    'rate': 'Rate',
    'wallet': 'Wallet',
    'profile': 'Profile',
    'certify&exp': 'Certification and expertise',
    'certifies': 'Certifies',
    'expertise': 'Expertise',
    'interests': 'Interests',
    'employerName': 'Employer name',
    'jobTitle': 'Job title',
    'messages': 'Messages',
    'writeMsg': 'Write your message here',
    'addDet': 'Ad details',
    'ChangePass': 'Change password',
    'socialAcc': 'Social accounts',
    'whatsApp': 'WhatsApp',
    'facebook': 'Facebook',
    'twitter': 'Twitter',
    'instagram': 'Instagram',
    'noAcc': 'Have no account? new registration',
    'add': 'Add',
    'addAd': 'Add ad',
    'jobName': 'Job name',
    'section': 'Section',
    'workType': 'Work type',
    'CompSug': 'Complaints and suggestions',
    'address': 'Sddress',
    'subTitle': 'Subject title',
    'subCont': 'Subject content',
    'edit': 'Edit',
    'delete': 'Delete',
    'cancel': 'Cancel',
    'yes': 'Yes',
    'no': 'No',
    'date': 'Date',
    'time': 'Time',
    'location': 'Location',
    'searchPlaceholder': 'Type what you want to look for',
    'activateAcc': 'Activate the account',
    'jobDet': 'Job details',
    'perHour': 'Per hour',
    'noHour': 'Without the number of hours',
    'hoursNo': 'Hours',
    'pricePerHour': 'Price per hour',
    'finalFee': 'Final fee',
    'attachments': 'Attachments',
    'noteThat': 'Please note that when you click on the add ad, this means that you accept it and will be charged',
    'ofUrWallet': 'of your wallet balance',
    'adCongrats': 'Congratulations Your ad has been successfully added',
    'fare': 'Fare',
    'ownerLocation': 'This location is approximate to the advertisement the ad owner\'s location',
    'connectWithAd': 'Connect with the advertiser',
    'deleteAd': 'Are you sure you want to delete the ad?',
    'interestName': 'Name of interest',
    'city': 'City',
    'adNumber': 'Ad number',
    'activityName': 'Activity Name',
    'noteAdd': 'Please note that when you click on the ad, this means that you accept it and will be charged',
    'noCredit': 'Sorry there is not enough credit in the wallet, please recharge your wallet',
    'recharge': 'Recharge',
    'msgContent': 'Message content',
    'addCredit': 'Congratulations Your credit has been added successfully',
    'passRecovery': 'Password Recovery',
    'chooseLang': 'Choose language',
    'login': 'Login',
    'req&ann': 'orders and ads',
    'req': 'Orders',
    'ann': 'Ads',
    'urRate': 'Do not forget to put your rate',
    'currentBalance': 'Your current balance',
    'DR': 'DR',
    'reChargeWallet': 'Recharge the wallet',
    'bankInfo': 'You can recharge your balance by providing us with your bank account information',
    'transBank': 'Name of the transferring bank',
    'accUser': 'Account Holder\'s Name',
    'accNum': 'Account number',
    'chargedCredit': 'Amount to be charged',
    'transferReceipt': 'Image of the transfer receipt',
    'newReg': 'New registration',
    'agreement': 'By logging in to the app you agree to',
    'attention': 'Attention',
	'passwordRequired': 'Password is required',
	'phoneRequired': 'Phone is required',
	'passwordLength': 'Password less than 6 characters',
	'passwordNotMatch': 'New password and confirm password not match',
	'phoneValidation': 'Phone number is incorrect',
	'searchResult': 'Search Result',
	'categories': 'Categories',
	'countries': 'Countries',
	'activity': 'Activity',
	'editAd': 'Edit Ad',
	'noBalance': 'You Don\'t Have enough Balance To Add New Ad',
	'establishment': 'establishment',
	'individual': 'individual',
	'company': 'company',
	'other': 'other',
	'distance': 'far of',
	'km': 'km',
	'gender': 'gender',
	'male': 'male',
	'female': 'female',
	'both': 'both',
	'jobNameValid': 'job name has numbers',
	'activityValid': 'activity has numbers',
    'codeNotCorrect': 'code not correct',
    'verifyPassword': 'Password and Confirm Password do not match',
	'favs': 'Fav Categories',
	'noData': 'NO DATA',
	'subSection': 'Sub Section',
	'urMoney': 'Your money is added by dollars',
	'usernameRequired': 'user name is required',
	'bankTransfer': 'Bank Transfer',
	'onlinePayment': 'Online Payment',
	'successPayment': 'payment transaction done successfully',
	'error': 'something went wrong plz try again',
	'noBalanceAdd': 'There must be $ 1 to add your ad',
	'noBalanceReq': 'There must be $ 1 to request this ad',
	'appRate': 'Rate App',
}

export default en;
